### Site metadata
title: RK
author: Rafał Karoń
description: My portfolio
keywords: HTML, CSS, Python, Technical Writing, Techwriting, Technical Communication, Techcom, Information Development, Frontend, Backend, Scripts, Automation
since: 2020
logo: RK
baseurl: legacy-site-jekyll

### Contact data
contact:
  email: 
    id: 'rafalkaron@gmail.com'
    href: 'mailto:'
    title: 'Email'
    icon: "/assets/icons/email.svg"
    icon_dark: "/assets/icons/email_dark.svg"
  github: 
    id: 'rafalkaron'
    href: 'https://github.com/'
    title: 'GitHub'
    icon: "/assets/icons/github.svg"
    icon_dark: "/assets/icons/github_dark.svg"
  linkedin:
    id: 'rafał-karoń-39534516b'
    href: 'https://linkedin.com/in/'
    title: 'LinkedIn'
    icon: "/assets/icons/linkedin.svg"
    icon_dark: "/assets/icons/linkedin_dark.svg"
  twitter: 
    id: 'rafalkaron'
    href: 'https://twitter.com/'
    title: 'Twitter'
    icon: "/assets/icons/twitter.svg"
    icon_dark: "/assets/icons/twitter_dark.svg"
  500px:
    id: 'rafalkaron'
    href: 'https://500px.com/'
    title: '500px'
    icon: "/assets/icons/500px.svg"
    icon_dark: "/assets/icons/500px_dark.svg"

### Site configuration
livereload: true
exclude: 
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - README.md
markdown: kramdown
kramdown:
  input: GFM
show_drafts: False

### github-pages-remote theme
plugins:
  - jekyll-remote-theme
remote_theme: rafalkaron/r-jekyll-theme@main

### Uncomment for gem-based theme
#theme: r-jekyll-theme
